### ISSUE TITLE
Discord webhook and random password generator

### ISSUE THREAD

**Issue by DuncanEll2** [Its-Scru/scru_serverlock#1]
Not an issue, lil enhancement with discord webhook and random password generating if you ever wanted to use

[scru_serverlockRPassword.zip](https://github.com/Its-Scru/scru_serverlock/files/10291163/scru_serverlockRPassword.zip)

![0TUSZS9](https://user-images.githubusercontent.com/120644682/209248474-8100a58e-9c66-4630-9fa4-a0287c3265ad.png)

**Comment by Its-Scru** [comment]
I may add something like that
