### ISSUE TITLE
[Suggestion] Add CFX license whitelist config

### ISSUE THREAD

**Issue by nzkfc** [Its-Scru/scru_serverlock#3]
Enable it so if people with a set CFX license connect, they skip the password.

Helps for staff going in and out all the time doing testing, but allows for them to invite people to test with the password etc.

**Comment by Its-Scru** [comment]
Thank you for the suggestion! I have added that to the script. Here is the latest commit: https://github.com/Its-Scru/scru_serverlock/commit/f6ea0a9fd268b70b32692e76ffe012dec8be8aaa
